### ISSUE TITLE
graph generation error

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#236] opened 2019-05-01 06:40 UTC
In `MathHub/MiKoMH/GenCS/source/codes/en/ASCII-problems.tex` we find 
```
\importmhmodule[path=dmath/en/functions]{myfunctions}
```
when I generate the graph for `MathHub/MiKoMH/IWGS/source/course/notes` the node `myfunctions` and all of its dependencies appear in blue instead of in green. 
The error seems to involve the differencre between the file name and the module id.

**Comment by jfschaefer** [comment] 2019-05-02 15:41
The cause of the wrong colours was that `\importmhmodule` always resulted in blue nodes. It should be fixed now (i.e. `\importmhmodule` is now treated like `\gimport` etc.).

**Closed** 2019-05-03 13:03 UTC
Labels: bug
