### ISSUE TITLE
errors in mikoslides.cls.ltxml

### ISSUE THREAD

**Issue by cmaeder** [KWARC/sTeX#103] opened 2015-07-02 08:13 UTC
latexml on any file from MiKoMH fails for me with:

```
maeder@lati:/var/data/localmh/MathHub/MiKoMH/ACS$ run-latexml.sh source/cfl/en/BNF.tex
3 errors; 2 fatal errors; 3 undefined macros[\metasetkeys, \newrobustcmd, \mhframeimage]
Error! Did not write file /var/data/localmh/MathHub/MiKoMH/ACS/source/cfl/en/BNF.omdoc
```

The content of `BNF.ltxlog` is:

```
(Loading profile /var/data/localmh/ext/perl5lib/lib/perl5/LaTeXML/resources/Profiles/stex-smglom-module.opt... )
(Loading profile /var/data/localmh/ext/perl5lib/lib/perl5/LaTeXML/resources/Profiles/stex-smglom-module.opt... )
Driver file for pgf: \pgfsysdriver



Error:undefined:\newrobustcmd The token T_CS[\newrobustcmd] is not defined.
        /var/data/localmh/ext/sTeX/sty/mikoslides/mikoslides.cls.ltxml line 109
        In Core::Stomach[@0x3b46de0] /var/data/localmh/ext/sTeX/sty/mikoslides/mikoslides.cls.ltxml line 109
         <= Core::Gullet[@0x3b48b98] <= \documentclass OptionalSemiverbatim S... <= Core::Stomach[@0x3b46de0] <= ...

Error:undefined:\mhframeimage The token T_CS[\mhframeimage] is not defined.
        /var/data/localmh/ext/sTeX/sty/mikoslides/mikoslides.cls.ltxml line 109
        In Core::Stomach[@0x3b46de0] /var/data/localmh/ext/sTeX/sty/mikoslides/mikoslides.cls.ltxml line 109
         <= Core::Gullet[@0x3b48b98] <= \documentclass OptionalSemiverbatim S... <= Core::Stomach[@0x3b46de0] <= ...

Error:undefined:\metasetkeys The token T_CS[\metasetkeys] is not defined.
        /var/data/localmh/ext/sTeX/sty/mikoslides/mikoslides.cls.ltxml line 109
        In Core::Stomach[@0x3b46de0] /var/data/localmh/ext/sTeX/sty/mikoslides/mikoslides.cls.ltxml line 109
         <= { <= Core::Stomach[@0x3b46de0] <= Core::Gullet[@0x3b48b98] <= ...

Fatal:die:/var/data/localmh/ext/sTeX/sty/mikoslides/mikoslides.cls.ltxml File /var/data/localmh/ext/sTeX/sty/mikoslides/mikoslides.cls.ltxml had an error:
        /var/data/localmh/ext/sTeX/sty/mikoslides/mikoslides.cls.ltxml
          
        Fatal:misdefined:# The token T_PARAM[#] should never reach Stomach!
                /var/data/localmh/ext/sTeX/sty/mikoslides/mikoslides.cls.ltxml line 109
                In Core::Stomach[@0x3b46de0] /var/data/localmh/ext/sTeX/sty/mikoslides/mikoslides.cls.ltxml line 109
                 <= { <= Core::Stomach[@0x3b46de0] <= { <= ...
        3 errors; 1 fatal error; 3 undefined macros[\metasetkeys, \newrobustcmd, \mhframeimage] at /var/data/localmh/ext/perl5lib/lib/perl5/LaTeXML/Common/Error.pm line 69, <$IN> line 2.
        Next token is T_OTHER[1]
        In Core::Gullet[@0x3b48b98] /var/data/localmh/ext/sTeX/sty/mikoslides/mikoslides.cls.ltxml
         <= \documentclass OptionalSemiverbatim S... <= Core::Stomach[@0x3b46de0] <= ...
3 errors; 2 fatal errors; 3 undefined macros[\metasetkeys, \newrobustcmd, \mhframeimage] at /var/data/localmh/ext/perl5lib/lib/perl5/LaTeXML/Common/Error.pm line 69, <$IN> line 2.


Conversion complete: 3 errors; 2 fatal errors; 3 undefined macros[\metasetkeys, 
\newrobustcmd, \mhframeimage].
Status:conversion:3
```

**Comment by kohlhase** [comment] 2015-07-02 08:20
this seems to be a regression introduced by Jinbo, it seems that some of the LaTeX stuff from the DTX leaks into the generated style file. Assigning to him.

**Comment by La-Stravaganza** [comment] 2015-07-02 12:42
Yes, this is caused by my recent pushes.
![selection_005](https://cloud.githubusercontent.com/assets/10081485/8477126/0bbb50a0-20c8-11e5-8f78-3e55e2c9c142.png)

I substitute (nearly) all ``newcommand`` with ``newrobustcmd`` in ``etoolbox.sty``, probably ``etoolbox`` is    not supported by latexml? @angerhang 

Right now we can 2 options:
  1. Change them back
  2. Try to make latexml support latexml

**Comment by cmaeder** [comment] 2015-07-02 12:50
/usr/share/texlive/texmf-dist/tex/latex/etoolbox/etoolbox.sty is installed on my machine. Does it need to be mentioned somewhere?

**Comment by La-Stravaganza** [comment] 2015-07-02 12:53
Yes, I think for latexml side, there should be a binding called ``etoolbox.sty.ltxml`` under ``/path/to/localmh/ext/LaTeXML/lib/LaTeXML/Package``.

pdflatex side works fine.

**Comment by cmaeder** [comment] 2015-07-02 13:04
Can etoolbox.sty.ltxml be created from etoolbox.sty?

**Comment by La-Stravaganza** [comment] 2015-07-02 13:05
Not automatically, @angerhang needs to write ``etoolbox.sty.latexml`` by hand.

**Comment by cmaeder** [comment] 2015-07-02 13:09
Maybe changing back to \newcommand is the simplest solution for a stable branch.

**Comment by cmaeder** [comment] 2015-07-02 13:16
It is best to make a new branch for reverting the \newrobustcmd changes, so that we can test first.

**Comment by La-Stravaganza** [comment] 2015-07-02 14:17
Solved.

**Comment by kohlhase** [comment] 2015-07-02 15:19
I have not looked, but you should use

**Comment by cmaeder** [comment] 2015-07-10 10:07
Currently I use (MMT uses) the branch "without_etoolbox" with the patch https://github.com/KWARC/sTeX/commit/0a63821d791b6b3fdc8121574dec33ea280c8244. It seems to work for LaTeXML and pdflatex. (pdflatex still includes etoolbox.sty.)

Whould there be any advantage of using  `\newrobustcommand` for pdflatex?

side note: for the BNF example, LaTeXML produces the BNF.ltxlog content below,
and in BNF.pdf the non-terminal `NP` can not be distinguished from single letter non-terminals `N`, `P`, and `V` (or only by the fact that the left-hand-side of a grammar rule should be exactly one non-terminal)

```
(Loading profile /var/data/localmh/ext/perl5lib/lib/perl5/LaTeXML/resources/Prof
iles/stex-smglom-module.opt... )
(Loading profile /var/data/localmh/ext/perl5lib/lib/perl5/LaTeXML/resources/Prof
iles/stex-smglom-module.opt... )
Driver file for pgf: \pgfsysdriver



Error:expected:{} Missing argument {} for \language@active@arg" {}
        /var/data/localmh/MathHub/MiKoMH/GenCS/source/codes/en/string-math.sms#textrange(from=9;1,to=10;94)
        Input is empty
        Input is empty
        In \language@active@arg" {} from /usr/share/texlive/texmf-dist/tex/generic/babel-german/ngermanb.ldf#textrange(from=88;0,to=88;24)
         <= Core::Gullet[@0x4e8c368] <= Core::Stomach[@0x4e1bf20] <= \text {} <= ...

Error:expected:{} Missing argument {} for \language@active@arg" {}
        /var/data/localmh/MathHub/MiKoMH/GenCS/source/codes/en/string-math.sms#textrange(from=9;1,to=10;94)
        Input is empty
        Input is empty
        In \language@active@arg" {} from /usr/share/texlive/texmf-dist/tex/generic/babel-german/ngermanb.ldf#textrange(from=88;0,to=88;24)
         <= Core::Gullet[@0x4e8c368] <= Core::Stomach[@0x4e1bf20] <= \text {} <= ...

Error:expected:{} Missing argument {} for \language@active@arg" {}
        /var/data/localmh/MathHub/MiKoMH/GenCS/source/codes/en/string-math.sms#textrange(from=10;1,to=11;103)
        Input is empty
        Input is empty
        In \language@active@arg" {} from /usr/share/texlive/texmf-dist/tex/generic/babel-german/ngermanb.ldf#textrange(from=88;0,to=88;24)
         <= Core::Gullet[@0x4e8c368] <= Core::Stomach[@0x4e1bf20] <= \text {} <= ...

Error:expected:{} Missing argument {} for \language@active@arg" {}
        /var/data/localmh/MathHub/MiKoMH/GenCS/source/codes/en/string-math.sms#textrange(from=10;1,to=11;103)
        Input is empty
        Input is empty
        In \language@active@arg" {} from /usr/share/texlive/texmf-dist/tex/generic/babel-german/ngermanb.ldf#textrange(from=88;0,to=88;24)
         <= Core::Gullet[@0x4e8c368] <= Core::Stomach[@0x4e1bf20] <= \text {} <= ...

Conversion complete: 4 errors.

Post-processing complete: No obvious problems
Status:conversion:2 
```

**Comment by La-Stravaganza** [comment] 2015-07-11 21:25
The command with ``\newrobustcmd`` will be robust, as the manual suggests. 

The difference between ``\newrobustcmd`` and ``\newcommand`` is maybe not so clear, but there are some  very useful command sequences in ``etoolbox``,  such as ``\csuse`` or ``\csdef``, which can save us from multiple ``expandafter``s.

Other advantages are still waiting to discover, before I am sure that pdflatex side will be safe, I won't use them in sTeX.

**Comment by cmaeder** [comment] 2015-07-13 08:42
I don't think MMT should checkout the proper branch of this repository prior to running latexml resp. pdflatex, do you?

**Comment by La-Stravaganza** [comment] 2015-07-25 16:53
After recent merge #115 this shouldn't be a problem right now. I will take care for any error caused by ``RawTeX`` afterwards.

**Closed by La-Stravaganza** 2015-07-25 16:53 UTC
